services:
  
  nginx:
    image: nginx:stable-alpine3.24
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - grafana
      - prometheus

  app:
    build:
      context: ./go-app
      dockerfile: Dockerfile
    container_name: go-app
    restart: unless-stopped
    environment:
      PORT: ${PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      migrations:
        condition: service_completed_successfully

  migrations:
    image: migrate/migrate:v4.17.0
    container_name: migrations
    volumes:
      - ./go-app/schema:/migrations
    command:
      - '-path=/migrations'
      - '-database=postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable'
      - 'up'
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:v3.15.0
    container_name: prometheus
    restart: unless-stopped
    expose:
      - "9090"
    volumes: 
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
#      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--web.external-url=http://${SERVER_IP}/prometheus/'

  grafana:
    image: grafana/grafana:13.2.2
    container_name: grafana
    restart: unless-stopped
    expose:
      - "3000"
    volumes: 
      - grafana_data:/var/lib/grafana
    environment: 
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_SERVER_ROOT_URL: http://${SERVER_IP}/grafana/
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"

  node-exporter:
    image: prom/node-exporter:v1.12.1
    container_name: node-exporter
    restart: unless-stopped
    expose:
      - "9100"
    command:
      - '--path.rootfs=/rootfs'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    restart: unless-stopped
    expose:
      - "8080"
    volumes: 
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    command:
      - '--add_dir_header=true'

#  alertmanager:
#    image: prom/alertmanager:v0.34.1
#    container_name: alertmanager
#    restart: unless-stopped
#    expose:
#      - "9093"
#    volumes:
#      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro 
#      - alertmanager_data:/alertmanager
#    command:
#      - '--config.file=/etc/alertmanager/alertmanager.yml'
#      - '--storage.path=/alertmanager'

#  telegram-bot:
#    image: metalmatze/alertmanager-bot:0.4.3
#    container_name: telegram-bot
#    restart: unless-stopped
#    environment:
#      ALERTMANAGER_URL: http://alertmanager:9093
#      TELEGRAM_ADMIN: ${TELEGRAM_ADMIN}
#      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
#    command:
#      - '--store=bolt'
#      - '--bolt.path=/data/bot.db'
#    volumes:
#      - bot_data:/data

  loki:
    image: grafana/loki:3.6.0
    container_name: loki
    restart: unless-stopped
    expose:
      - "3100"
    command: 
      - '-config.file=/etc/loki/loki-config.yml'
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki_data:/loki
    depends_on:
      loki-init:
        condition: service_completed_successfully

  loki-init:
    image: alpine:3.22
    container_name: loki-init
    user: "0:0"
    volumes:
      - loki_data:/loki
    command: "chown -R 10001:10001 /loki"

  alloy:
    image: grafana/alloy:v1.11.2
    container_name: alloy
    restart: unless-stopped
    user: "0:0"
    group_add:
      - "995"
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - alloy_data:/var/lib/alloy/data
    depends_on:
      - loki

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
#  alertmanager_data:
#  bot_data:
  alloy_data:
  loki_data:
